name: test_widgets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_exit_app: ^1.1.2
  flutter_native_splash: ^2.3.10
  flutter_zoom_drawer: ^3.2.0
  image_picker: ^1.0.7
  objectbox: ^2.5.0
  objectbox_flutter_libs: any
  path: ^1.8.3
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets:
   - assets/images/profile_img01.png
   - assets/images/profile_img02.jpeg